apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-nginx-deployment
  labels:
    app: form-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-nginx
  template:
    metadata:
      labels:
        app: form-nginx
    spec:
      containers:
      - name: frontend
        image: gskanishkar/frontend:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: form-nginx-service
spec:
  selector:
    app: form-nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
